### ISSUE TITLE
Where do the files get created?

### ISSUE THREAD

**Issue by firefoxlover** [nnsee/payload-dumper#1]
It seems to run perfectly but I dont know where the results are stored, nor can I find an argument to define that. 

They dont appear in the same folder as the payload.bin

**Comment by nnsee** [comment]
They should be in the current working directory (the directory where the script is run from, not where the payload file itself is) in a directory named `output` - but you can customize this by setting the `--out` parameter, for example `--out $HOME/dump`. Feel free to reopen this issue if you're still having trouble.
